/* This file is autogenerated by ./configure -- do not edit! */
#define POPCNT_INTRINSICS
#define HAVE_BLAS 0
#define HAVE_TLS 1
#define HAVE_FENV 1
#define HAVE_PTHREAD 1
#define HAVE_GC 0
#define FLINT_REENTRANT 0
#define WANT_ASSERT 0
#ifdef FLINT_USE_DLL
#define FLINT_DLL __declspec(dllimport)
#else
#define FLINT_DLL __declspec(dllexport)
#endif
